server:
  port: 8090
spring:
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: sa
    password: ''
  h2:
    console:
      enabled: true
  application:
    name: "loans"
  config:
    import: "optional:configserver:http://localhost:8071"
  cloud:
    kubernetes:
      discovery:
        all-namespaces: true
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
    show-sql: true

  profiles:
    active: "prod"

management:
  endpoints:
    web:
      exposure:
        include: "*"
  metrics:
    tags:
      application: "loans"
  info:
    env:
      enabled: true
  health:
    livenessstate:
      enabled: true
    readinessstate:
      enabled: true
  endpoint:
    health:
      probes:
        enabled: true
      show-details: always
    shutdown:
      enabled: true

endpoints:
  shutdown:
    enabled: true


info:
  app:
    name: "loans"
    description: "Loans Application"
    version: "1.0.0"

logging:
  level:
    com:
      example:
        loans: DEBUG
  pattern:
    level: "%5p[loans,%X{trace_id},%X{span_id}]"
